FROM python:3.10.4

WORKDIR /api

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "app:app", "--host", "127.0.0.1", "--port", "8080", "--reload"]