services:
  fastapi:
    build:
      context: .
      dockerfile: api/Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api

  streamlit:
    build:
      context: .
      dockerfile: streamlit/Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    volumes:
      - ./streamlit:/streamlit
    environment:
      - RUNNING_IN_DOCKER=true